# Generated by Django 5.1.2 on 2024-10-31 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservationdate',
            field=models.DateField(default=datetime.date(2024, 11, 1)),
        ),
        migrations.AddField(
            model_name='user',
            name='reservationtime',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tablenumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='Doe', max_length=255),
        ),
    ]
