# Generated by Django 5.1.2 on 2024-11-10 00:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_user_password_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablenum', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date(2024, 11, 1))),
                ('time', models.TimeField(default=datetime.time(19, 0))),
                ('available', models.BooleanField(default=True)),
                ('reservedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.user')),
            ],
            options={
                'unique_together': {('tablenum', 'date', 'time')},
            },
        ),
    ]
