# Generated by Django 5.1.3 on 2024-11-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_reservation_reservedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='starttime',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('tablenum', 'date', 'time')},
        ),
    ]
