# Generated by Django 5.1.2 on 2024-12-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_reservation_date'),
        ('pages', '0007_reservation_is_active_alter_reservation_date'),
    ]

    operations = [
    ]
