# Generated by Django 5.1.2 on 2024-11-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_reservation_is_active_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
